apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-springboot-app
  labels:
    app: category-springboot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-springboot-app
  template:
    metadata:
      labels:
        app: category-springboot-app
    spec:
      containers:
        - name: category-springboot-app
          image:  ritik109/category-service-app:0.0.1
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: category-app-service
spec:
  selector:
    app: category-springboot-app
  ports:
  - port: 8082
    targetPort: 8082
